config/routes.rb
            get :sharing_insights
          end
          resources :event_definitions, only: %i[new create edit update destroy], path: 'events' do
            resources :shares, only: %i[new create]
            get :sharing_insights
            get :clone, on: :member
          end
          resources :event_feeds, except: [:index] do
            post :reprocess, on: :member
            resources :imported_event_definitions, except: [:show, :index, :new, :create]
          end
          resource :event_import_notifications, only: %i[edit update]
          resources :event_imports, only: :index do
            post :import_all, on: :collection
            post :import, on: :member
          end
          # TODO - Add jobs here
          resources :jobs, only: %i[new create edit update destroy] do
            resources :shares, only: %i[new create]
            get :sharing_insights
            get :clone, on: :member
          end
          resources :galleries, only: %i[new create edit update destroy] do
            resources :shares, only: %i[new create]
            get :sharing_insights
          end
          resources :images, only: %i[index edit update destroy]
          resources :pdfs
          resources :category_tag_management, only: [:index] do
            collection do
              post :create_content_category
              post :create_content_tag
              get :new_content_category
              delete :delete_content_category
              delete :delete_content_tag
            end
          end
          resources :offers, only: %i[new create edit update destroy] do
            resources :shares, only: %i[new create]
            get :sharing_insights
            get :clone, on: :member
          end
          resources :posts, only: %i[new create edit update destroy] do
            resources :shares, only: %i[new create]
            get :clone, on: :member
            get :sharing_insights
          end
          resources :quick_posts, only: %i[new create edit update destroy] do
            resources :shares, only: %i[new create]
            get :sharing_insights
            get :clone, on: :member
          end
          resources :creation_posts, only: %i[new create edit update destroy] do
            # resources :shares, only: %i[new create]
            # get :sharing_insights
            # get :clone, on: :member
          end
          resources :profile_posts, only: %i[new create edit update destroy] do
            # resources :shares, only: %i[new create]
            # get :sharing_insights
            # get :clone, on: :member
          end
        end


        namespace :data do
          root to: 'roots#show'
          resource :alert, only: %i[edit update]
          resource :customers, only: %i[edit update]
          resource :delivery, only: %i[edit update]
          resource :details, only: %i[edit update]
          resource :lines, only: %i[edit update]
          resource :location, only: %i[edit update]
          resource :openings, only: %i[edit update]
          resource :social_profiles, only: %i[edit update]
          resource :team_members_positions, only: %i[edit update]
          resource :values, only: %i[edit update]
          resources :team_members, only: %i[index new create edit update destroy]
        end

        namespace :crm do
          root to: 'roots#show'
          resource :contact_message_notifications, only: %i[edit update]
          resource :feedbacks_automation, only: %i[update]
          resource :review_notifications, only: %i[edit update]
          resource :reviews_automation, only: %i[update]
          resources :contact_messages, only: %i[index show destroy]
          resources :contacts, only: %i[index new create edit update destroy] do
            resources :feedbacks, only: %i[new create]
            resources :crm_notes, only: %i[new create edit update destroy]
          end
          resources :imports, only: %i[index update] do
            collection do
              get 'download_contact_template'
              get 'download_company_template'
              get '/import_status_check/:job_id', action: :import_status_check, as: :import_status_check
              post 'review'
              post 'review_duplicates'
              post 'process_csv'
              post 'match_columns'
            end
          end
          resources :company_lists, only: %i[index new create edit update destroy]
          get 'company_lists/following', to: 'following#index'
          resources :follower_notifications, only: [] do
            collection do
              get :edit
              patch :update
            end
          end
          resources :contact_forms, only: %i[index new create edit update destroy]
          resources :form_submissions, only: %i[index show destroy]
          resources :companies, only: %i[index new create edit update destroy] do
            resources :business, only: %i[new create edit update]
            resources :crm_notes, only: %i[new create edit update destroy]
          end
          resources :feedbacks, only: %i[index new create show destroy] do
            resource :review_invitation, only: %i[create]
          end
          resources :reviews, only: %i[index show destroy] do
            resource :review_publication, only: %i[create destroy]
          end
          resources :invites, only: %i[index new create]
        end

        namespace :tools do
          root to: 'roots#index'
          resources :review_widgets, only: %i[index new create edit update destroy]
          resources :directory_widgets, only: %i[index new create edit update destroy]
          resources :content_feed_widgets, only: %i[index new create edit update destroy]
          resources :calendar_widgets, only: %i[index new create edit update destroy]
          resources :mercantile_embeds, only: %i[index new create edit update destroy]
        end

        namespace :website do
          root to: 'roots#show'
          resource :about_page, only: %i[edit update]
          resource :add_website, only: [:none] do
            collection do
              get :new_website
              match 'upgrade_to_new_plan', via: [:get, :post]
            end
          end
          resource :blog_page, only: %i[edit update]
          resource :contact_page, only: %i[edit update]
          resource :details, only: %i[edit update]
          resource :home_page, only: %i[edit update]
          resource :menus, only: %i[edit update]
          resource :meta, only: %i[edit update]
          resource :sidebars, only: %i[edit update]
          resource :theme, only: %i[edit update] do
            get :manage_fonts
          end
          resources :custom_pages, only: %i[new create edit update]
          resources :redirects, only: %i[index new create edit update destroy]
          resources :webpages, only: %i[index destroy] do
            get :table, on: :collection
            resource :publications, only: %i[create destroy]
          end
        end

        namespace :accounts do
          root to: 'roots#show'
          resource :locable, only: %i[edit update destroy]
          resource :facebook, only: %i[edit update destroy]
        end

        resource :marketing, only: %i[show]
        resources :marketing_assistant, only: :index
        resource :super_settings, only: %i[edit update] do
          post 'create_affiliation', on: :member
          delete 'delete_affiliation', on: :member
          post 'add_legacy_plan', on: :member
          delete 'delete_legacy_plan', on: :member
          post 'associate_with_affiliate', on: :member
        end
        resources :alliances, only: %i[index]
        resources :authorizations, only: %i[index new create destroy update]
        resources :images, only: %i[index]
        resources :content_categories, only: %i[new create]
        resources :content_tags, only: %i[index create]
        resources :orders, only: [:index, :show, :create, :update]
        resources :products, only: %i[index new create edit update destroy] do
          resource :archive, only: [:create, :destroy], controller: 'archive_products'
        end
        resources :reminders, only: :index
        resources :activity_calendar, only: :index do
          get :timeline, on: :collection
        end
        resources :mission_instance_comments, only: :create
        resources :mission_notes, only: :update
        resources :mission_notifications, only: [] do
          collection do
            get :edit
            put :update
          end
        end
        resources :to_do_lists do
          post :add_mission, on: :member
          post :remove_mission, on: :member
        end
        resources :missions, only: %i[index show] do
          get :custom, on: :collection
          resources :mission_assignments, only: :create
        end
        resources :mission_histories, only: :index
        resources :mission_instances, only: %i[edit update create new] do
          collection do
            post :complete
            post :skip
            post :snooze
            post :deactivate
            post :activate
            post :update_list
          end
        end
        resources :to_dos, only: %i[index show create update destroy] do
          resources :comments, only: :create

          member do
            put :submit_for_review
            put :mark_as_complete
            put :remove
            put :reactivate
          end

          collection do
            resources :notification_settings, only: %i[index update]
          end
        end
      end
    end

    resources :locations, only: %i[index new create]
  end

  namespace :async do
    get 'calendar', to: 'widgets#calendar'
    get 'quick_post', to: 'widgets#quick_post'
  end

  scope module: :website, as: :website, constraints: WebsiteConstraint.new do
    root to: 'home_pages#show'
    get '/robots.:format' => 'robots#robots'

app/controllers/businesses/crm/business_controller.rb
class Businesses::Crm::BusinessController < Businesses::BaseController
  def edit
    @company = Company.find(params[:company_id])
    @business = Business.find(params[:business_id])
  end
#  def update
#    company = Company.find(params[:company_id])
#    @business = Business.find(params[:business_id])
#    if company.update(company_business_params)
#      redirect_to [@business, :crm_companies]
#    else
#      render 'business_edit'
#    end
#  end

  private

  def company_business_params
    params.require(:company).permit(:private_details, :business_attributes => [:name, :description, :website_url, 
      :website_url, :facebook_id, :google_plus_id, :linkedin_id, :twitter_id, :youtube_id, :citysearch_id, :instagram_id, 
      :pinterest_id, :yelp_id, :foursquare_id, :zillow_id, :opentable_id, :trulia_id, :realtor_id, :tripadvisor_id, :houzz_id],
      :location_attributes => [:name, :email, :street1, :street2, :city, :state, :zip_code, :phone_number])
  end
end

app/controllers/businesses/crm/companies_controller.rb
class Businesses::Crm::CompaniesController < Businesses::BaseController
  before_action only: new_actions do
    @company = @business.owned_companies.new
  end

  before_action only: member_actions do
    @company = @business.owned_companies.find(params[:id])
    @company.update_column :read_by, @company.read_by + [current_user.id] unless @company.read_by.include?(current_user.id)
  end

  def index
    scope = @business.owned_companies.includes(business: [:location])
    query = params[:query].to_s.strip

    if query.present?
      scope = scope.where('companies.name ILIKE ?', "%#{query}%")
    end

    @companies = scope.order(companies_order) #.page(params[:page]).per(20)

    respond_to do |format|

      # @businesses = Business.includes(:communities).order("id").search(params[:search]) #.page(params[:page]).per(20)
      format.html
      # format.json {render @businsses.as_json(only: [:id, :name, :communities.map(&:label).join(', '), :owned_companies.count, :in_impact, :merge, :updated_at])}
      format.json {render json: BusinessCrmCompaniesDatatable.new(view_context)}

    end
  end

  def new
    render template: 'businesses/crm/companies/_new', layout: false if params['query'] == 'modal'
  end

  def create
    if params[:search_add] == 'true'
      @companies = Business.where("name ILIKE ?", "%#{params[:name]}%")
      if @companies.length < 1 or params[:force] == 'true'
        company = Company.create_with_associations(params, @business) do |success|
          if success
            # flash[:appcues_event] = "Appcues.track('added company')"
            intercom_event 'added-company'
          end
        end
        if params[:json] == 'true'
          data = {}
          data[:object] = company
          data[:partial] = render_to_string(
            partial: 'businesses/crm/companies/business_form',
            locals: {
              disabled: company.not_editable?(@business),
              company: company,
              business: @business
            }
          )
          render json: data.to_json, layout: false
        else
          redirect_to [:edit, @business, :crm, company, company.business]
        end
      end
    elsif params[:add] == 'true'
      company = Company.where(:user_business_id => @business.id, :company_business_id => params[:new_business_id]).first
      if company.nil?
        new_business = Business.find(params[:new_business_id])
        company = Company.new(:user_business_id => @business.id, :company_business_id => new_business.id, :name => new_business.name,
                             :company_location_attributes => {:name => new_business.name})
        company.save
      end
      if params[:json] == 'true'
        render json: company.to_json, layout: false
      else
        # flash[:appcues_event] = "Appcues.track('added company')"
        intercom_event 'added-company'
        redirect_to [:edit, @business, :crm, company]
      end
    end
  end

  def update
    company = Company.find(params[:id])
    if !params[:company][:business_attributes].nil? && !company.business.in_impact
      if company.update_attributes(company_business_params)
        #redirect_to [@business, :crm_companies]
        if params[:json] == 'true'
          render json: company.to_json, layout: false
        else
          redirect_to [:edit, @business, :crm, company], :notice => "Successfully Saved Company"
        end
      else
        Rails.logger.info(company.errors.messages.inspect)
        redirect_to [:edit, @business, :crm, company], :notice => "Failed To Save Company"
      end
    else
      if company.update_attributes(company_params)
        if params[:json] == 'true'
          render json: company.to_json, layout: false
        else
          redirect_to [:edit, @business, :crm, company], :notice => "Successfully Saved Company"
        end
      else
        render 'edit'
      end
    end
  end

  def destroy
    Company.destroy(@company.id)
    redirect_to [@business, :crm_companies]
  end

  private

  def company_params
    params.require(:company).permit(
      :private_details, :name, :description, :website_url, :website_url, :facebook_id, :google_plus_id, :linkedin_id,
      :twitter_id, :youtube_id, :citysearch_id, :instagram_id, :pinterest_id, :yelp_id, :foursquare_id, :zillow_id,
      :opentable_id, :trulia_id, :realtor_id, :tripadvisor_id, :houzz_id,
      crm_notes_attributes: [ :content, ],
      :contact_ids => [],
      :company_list_ids => [],
      :company_location_attributes => [:name, :email, :street1, :street2, :city, :state, :zip_code, :phone_number]
    ).tap do |safe_params|
      if safe_params[:crm_notes_attributes]
        safe_params[:crm_notes_attributes].map do |_, attr|
          attr[:user_name] = current_user.name if attr[:content].present?
        end
      end
    end
  end
  def company_business_params
    params.require(:company).permit(:private_details, :business_attributes => [:name, :description, :website_url,
      :website_url, :facebook_id, :google_plus_id, :linkedin_id, :twitter_id, :youtube_id, :citysearch_id, :instagram_id,
      :pinterest_id, :yelp_id, :foursquare_id, :zillow_id, :opentable_id, :trulia_id, :realtor_id, :tripadvisor_id, :houzz_id,
      :logo_placement_attributes => [:id, :kind, :_destroy, :image_id, :image_attachment_cache_url, :image_attachment_content_type, :image_attachment_file_name, :image_attachment_file_size, :image_alt, :image_title],
      :location_attributes => [:id, :name, :email, :street1, :street2, :city, :state, :zip_code, :phone_number]]).deep_merge(
        business_attributes: {
          logo_placement_attributes: {
            image_user: current_user,
            image_business: @business,
          },
        },
      )
  end

  def business_update_params
    params[:company].require(:business_attributes).permit(:name, :description, :website_url)
  end

  def business_location_update_params
    params[:company][:business_attributes].require(:location_attributes).permit(:name, :email, :street1, :street2, :city, :state, :zip_code, :phone_number)
  end

  def companies_order
    if %w[name email phone_number].include?(params[:order_by])
      "#{params[:order_by]} #{companies_order_dir} NULLS LAST"
    else
      'CASE WHEN cardinality(read_by) = 0 THEN 0 ELSE 1 END ASC, updated_at DESC'
    end
  end

  def companies_order_dir
    if %w[asc desc].include?(params[:order_dir])
      params[:order_dir]
    else
      'desc'
    end
  end
end

app/controllers/businesses/crm/feedbacks_automations_controller.rb
class Businesses::Crm::FeedbacksAutomationsController < Businesses::BaseController
  def update
    update_resource @business, feedbacks_automation_params, location: [@business, :crm_feedbacks]
  end

  private

  def feedbacks_automation_params
    params.require(:business).permit(
      :automated_feedbacks_publishing,
    )
  end
end

app/views/businesses/crm/companies/_company.html.slim
/ - company_list = company_list_company.company_list

/ - is_in_crm = @business.owned_companies.any? { |company| company.company_business_id == company_list.business_id }
/ - is_following = @business.company_lists.any? { |list| list.companies.any? { |c| c.company_business_id == company_list.business_id}}

/ - params = { :referred_from => "following", :business => company_list.business_id, :business_name => company_list.business.name }
/ - add_to_network_link = link_to "Add to Network", [@business, :crm_companies, params]
/ - follow_back_link = link_to "Follow Back", [@business, :crm_company_lists, params]
/
/ - calendar = company_list.calendar_widgets.empty? ? nil : 'Calendar'
/ - directory = company_list.directory_widgets.empty? ? nil : 'Directory'
/ - content_feed = company_list.content_feed_widgets.empty? ? nil : 'Content Embed'
/ - types = [calendar, directory, content_feed].select { |x| x.present? }
/ - explicit_types = types.length > 3 ? types[0..1].join(', ') : types[0..2].join(', ')
/ - more_types = types.length > 3 ? " +#{types.length - 2} More" : ""


/ tr class=('unread' unless company.read_by.include?(current_user.id))
tr
  td = link_to company.business.name, [:edit, @business, :crm, company]
  / td
  /   - if company.business.in_impact
  /     | Claimed
  /   - else
  /     | Unclaimed
  /     / = link_to new_business_crm_invite_path(@business, company_id: company.id), class: 'btn btn-xs btn-default' do
  /     /   => icon 'envelope'
  /     /   | Invite

  td
    - if company.company_lists.count >= 1
      = "In #{company.company_lists.count} Local Networks"
    -else
      / - if is_following
      /   = link_to "Support Back", [@business, :crm_company_lists], class: 'btn btn-success btn-sm'
      / -else
      = link_to "Add to Network", [@business, :crm_company_lists], class: 'btn btn-success btn-sm'

  td
    - if company.business.in_impact
      | Claimed
    - else
      = link_to new_business_crm_invite_path(@business, company_id: company.id), class: 'btn btn-xs btn-default' do
        => icon 'envelope'
        | Request Support
  td
    = company.business.get_estimated_reach
  td = link_to("#{company.business.website_url}", company.business.website_url, target: '_blank')
  td = company.business.location.phone_number? ? company.business.location.phone_number : '--'
  td = company.business.location.street1
  td = company.business.location.city
  td = company.business.location.state
  td
    = link_to [@business, :crm, company], class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do
      => icon 'times-circle'
      | Delete
  / new_business_crm_invite_path

app/views/businesses/crm/companies/_crm_note_activity.html.slim
.vertical-timeline-block
  .vertical-timeline-icon.blue-bg
    i.fa.fa-pencil

  .vertical-timeline-content
    p
      = link_to [@business, :crm, @company, subject], class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do
        => icon 'times-circle'
        | Delete
      = link_to [:edit, @business, :crm, @company, subject], class: 'btn btn-xs btn-default m-r-5px' do
        => icon 'pencil'
        | Edit
      
    p = subject.content
    p.small.text-muted by #{subject.user_name} #{time_ago_in_words subject.created_at} ago
    / p = subject.content
    / = activity_time_tag(subject)
javascript:
  //Override the default confirm dialog by rails
  $.rails.allowAction = function(link){
    if (link.data("confirm") == undefined){
      return true;
    }
    $.rails.showConfirmationDialog(link);
    return false;
  }

  //User click confirm button
  $.rails.confirmed = function(link){
    link.data("confirm", null);
    link.trigger("click.rails");
  }

  //Display the confirmation dialog
  $.rails.showConfirmationDialog = function(link){
    var message = link.data("confirm");
    swal({
      title: message,
      text:  'This action cannot be reversed.',
      type: 'warning',
      confirmButtonText: 'Delete',
      confirmButtonColor: '#DD6B55',
      showCancelButton: true
    }, function(confirmed) {
      if (confirmed) {
        $.rails.confirmed(link);
      }
    });
  };

app/views/businesses/crm/companies/_new.html.slim
#js-new-company-container
  = errors_for company
  = form_tag [@business, :crm_companies], method: :post, id: 'js-company-new'
    = hidden_field_tag :json , true
    = hidden_field_tag :force , true
    = hidden_field_tag :search_add , true
    = react_component "CRMLookup", business_id: @business.id, json: true, url: business_crm_companies_url(@business)

#js-edit-company-container

- content_for :javascript do
  javascript:
    var editId = 0;
    $('#js-company-new-modal button[class="close"]').click(function () {
      $('#js-company-new-modal').modal('hide');
    });
    $('#js-company-new-modal').on('hide.bs.modal', function(event) {
      $('#js-new-company-container').show();
      $('#js-edit-company-container').html("");
    });
    $("#js-new-company-container").on('click', 'a[data-method="post"]', function(event) {
      event.preventDefault()
      event.stopPropagation();
      jqxhr = $.ajax({
        type: 'POST',
        url: event.target.href,
        beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')); },
        cache: false,
        data: $(this).serialize(),
        dataType: 'html',
      });
      jqxhr.done(function(rawdata) {
        var data = JSON.parse(rawdata);
        editId = data.id
        let vals = $('#company_list_company_ids').val() || []
        $('#js-company-new')[0].reset();
        $('#js-company-new-modal').modal('hide');
        // checking if the select element already contains the value
        if( $('#company_list_company_ids option').filter((i, el) => el.value === `${data.id}`).length === 0 ) {
          $('#company_list_company_ids').append(
            $('<option value="'+data.id+'">'+data.name+'</option>')
          );
        }
        vals.push(`${data.id}`)
        let unique = vals.filter((v, i, a) => a.indexOf(v) === i);
        $('#company_list_company_ids').val(unique);
        $(".company_ids:enabled").trigger("chosen:updated");
      });
    });
    $('#js-company-new').on('submit', function(event) {
      event.preventDefault()
      jqxhr = $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')); },
        cache: false,
        data: $(this).serialize(),
        dataType: 'html',
      });
      jqxhr.done(function(rawdata) {
        var data = JSON.parse(rawdata);
        editId = data.object.id
        let vals = $('#company_list_company_ids').val() || []
        $('#js-company-new')[0].reset();
        $('#js-new-company-container').hide();
        $('#js-edit-company-container').html(data.partial);
        $('#edit_company_'+editId).append("#{escape_javascript(hidden_field_tag :json, true)}");
        $('#edit_company_'+editId).on('submit', function(e) {
          e.preventDefault()
          jqxhr = $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')); },
            cache: false,
            data: $(this).serialize(),
            dataType: 'html',
          });
          jqxhr.done(function(rawdata) {
            $('#js-company-new-modal').modal('hide');
          });
        });

        // checking if the select element already contains the value
        if(vals.indexOf(`${data.id}`) === -1) {
          $('#company_list_company_ids').append(
            $('<option value="'+data.object.id+'">'+data.object.name+'</option>')
          );
          vals.push(`${data.object.id}`)
          let unique = vals.filter((v, i, a) => a.indexOf(v) === i);
          $('#company_list_company_ids').val(unique);
          $(".company_ids:enabled").trigger("chosen:updated");
        }
      });
    });

app/views/businesses/crm/companies/create.html.slim
- title 'Pick Company'

= render :partial => 'dashbreadcrumb', :locals => { :fn => 'Local Connections', :fp => :crm_root, :sn => 'All Companies', :sp => :crm_companies, :an => ' Edit Company'}


.row
  .col-sm-12
    .panel.panel-default
      .panel-heading
        h1 Looking for one of these companies?
      .panel-body.company-search-results
        .row
        - @companies.each do |company|
          .col-lg-3
            .contact-box.center-version
              = link_to company.name, business_crm_companies_path(:add => 'true', :new_business_id => company.id), :method => :post
              - unless company.location.nil?
                p = company.location.street1.to_s + " " + company.location.street2.to_s
                p = company.location.city.to_s + ", " + company.location.state.to_s + " " + company.location.zip_code.to_s
                p = company.location.phone_number.to_s
              p = link_to "This is it", business_crm_companies_path(:add => 'true', :new_business_id => company.id), :method => :post, :class => "btn btn-primary"
        .row
          .col-sm-12
            h2 If the address/details don't match, please add a new company.
          .col-sm-4.col-md-3
            = link_to "Add New Company", business_crm_companies_path(:search_add => 'true', :force => 'true', :name => params[:name]), :method => :post, :class => "btn btn-success"

app/views/businesses/crm/companies/index.html.slim
- title 'All Companies'

= render :partial => 'dashbreadcrumb', :locals => { :fn => 'Local Connections', :fp => :crm_root, :an => 'All Companies & Causes'}

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          / .pull-right
            / = form_tag [@business, :crm_companies], method: :get, style: 'float:left; margin-right:0.5em' do
            /   .form-group
            /     = label_tag :query, 'Query', class: 'sr-only'
            /     .input-group
            /       = text_field_tag :query, params[:query], class: 'form-control'
            /       span.input-group-btn
            /         = button_tag icon('search'), class: 'btn btn-default'
          = link_to [:new, @business, :crm_company], class: 'btn btn-sm btn-primary' do
            => icon 'plus-circle'
            | Add company
          = link_to polymorphic_url([@business, :crm_imports], :import_type => 'companies'), class: 'btn btn-sm btn-primary btn-outline pull-right' do
            => icon 'plus-circle'
            | Import contacts in bulk

          - if @companies.empty?
            .row
              .col-lg-4.col-lg-offset-4
                .p-a-3.text-center
                  = image_tag('https://assets.locable.com/r/thumbnail/09856f82-489e-4ef1-97ad-4aed4413e8d5/Connections%20&%20Community.png', style: 'max-height: 220px', class: 'img-responsive center-block')
                  h2 No Companies or Causes Found
                  h4
                    = link_to 'Add a Company', [:new, @business, :crm_company], class: 'text-navy'
                  p.text-left.m-t-md.strong Keep track of companies you endorse and causes you support.
                  p.text-left Go further by creating embeddable tools for your website like our self-updating directory, community calendar and more.
          - else
            / p style="margin:2em 0" = page_entries_info @companies
            table.table.table-stripped.serverside-datatable data-url="#{business_crm_companies_path(format: :json)}"
              thead
                tr
                  th
                    | Name
                  / th
                  /   | Status
                  th.no-sort
                    | Supporting
                  th.no-sort
                    | Supporters
                  th.no-sort
                    | Estimated Monthly Reach
                  th.no-sort
                    | Website
                  th.no-sort
                    | Phone
                  th.no-sort
                    | Address
                  th.no-sort
                    | City
                  th.no-sort
                    | State
                  th.no-sort
              tbody
                / = render @companies
          / = paginate @companies

javascript:
  //Override the default confirm dialog by rails
  $.rails.allowAction = function(link){
    if (link.data("confirm") == undefined){
      return true;
    }
    $.rails.showConfirmationDialog(link);
    return false;
  }

  //User click confirm button
  $.rails.confirmed = function(link){
    link.data("confirm", null);
    link.trigger("click.rails");
  }

  //Display the confirmation dialog
  $.rails.showConfirmationDialog = function(link){
    var message = link.data("confirm");
    swal({
      title: message,
      text:  'This cannot be reversed.',
      type: 'warning',
      confirmButtonText: 'Delete',
      confirmButtonColor: '#DD6B55',
      showCancelButton: true
    }, function(confirmed) {
      if (confirmed) {
        $.rails.confirmed(link);
      }
    });
  };

app/views/businesses/crm/companies/new.html.slim
- title 'Add Company'

= render :partial => 'dashbreadcrumb', :locals => { :fn => 'Local Connections', :fp => :crm_root, :sn => 'All Companies', :sp => :crm_companies, :an => ' Add Company'}



.ibox.float-e-margins
  .ibox-title
    h1.h4 Add a New Company
  .ibox-content
    = errors_for @company
    = form_tag [@business, :crm_companies], method: :post
      = hidden_field_tag :force , true
      = hidden_field_tag :search_add , true
      = react_component "CRMLookup", business_id: @business.id