config/routes.rb
    present_and_not_impact_subdomain = request.subdomain.present? && request.subdomains.first != 'impact' && request.subdomains.first != 'listings' && request.subdomains.first != 'www'

    !host_match || present_and_not_impact_subdomain
  end
end

class ListingConstraint
  def matches?(request)
    host_match = request.host.match(Regexp.escape("listings.locabledev.com"))
    listings_subdomain = request.subdomain.present? && request.subdomains.first == 'listings' && request.subdomains.first != 'www' && request.subdomains.first != 'impact'

    host_match || listings_subdomain
  end
end

Rails.application.routes.draw do

  mount StripeEvent::Engine, at: "/stripe_events", :via => :post

  resources :line_items, only: [:create, :update, :destroy]

  scope module: :listing, as: :listing, constraints: ListingConstraint.new do
    root to: 'listings#index'
    match '/:lookup', to: 'listings#index', via: :get
    match '/:lookup/cart', to: 'carts#index', :as => 'cart', via: :get
    match '/:lookup/cart/new', to: 'carts#new', :as => 'new', via: :get
    match '/:lookup/cart/create', to: 'carts#create', :as => 'create', via: :get
    match '/:lookup/cart/show', to: 'carts#show', :as => 'show', via: :get
    match '/:lookup/directories', to: 'directories#index', :as => 'directories', via: :get
    match '/:lookup/directories/:id', to: 'directories#show', :as => 'directory', via: :get
    match '/:lookup/calendars', to: 'calendars#index', :as => 'calendars', via: :get
    match '/:lookup/calendars/:id', to: 'calendars#show', :as => 'calendar', via: :get
    match '/:lookup/content', to: 'content#index', :as => 'contents', via: :get
    match '/:lookup/before_after/:content_type/', to: 'content#before_after', :as => 'before_after', via: :get
    match '/:lookup/offer/:content_type/', to: 'content#offer', :as => 'offer', via: :get
    match '/:lookup/post/:content_type/', to: 'content#post', :as => 'post', via: :get
    match '/:lookup/job/:content_type/', to: 'content#job', :as => 'job', via: :get
    match '/:lookup/quick_post/:content_type/', to: 'content#quick_post', :as => 'quick_post', via: :get
    match '/:lookup/event/:content_type/', to: 'content#event', :as => 'event', via: :get
    match '/:lookup/products', to: 'products#index', :as => 'products', via: :get
    match '/:lookup/products/:id', to: 'products#show', :as => 'product', via: :get
    match '/:lookup/reviews/create', to: 'reviews#create', :as => 'create_review', via: :post
    match '/:lookup/reviews/new', to: 'reviews#new', :as => 'new_review', via: :get
    match '/:lookup/reviews', to: 'reviews#index', :as => 'reviews', via: :get
    match '/:lookup/reviews/:id', to: 'reviews#show', :as => 'review', via: :get

    match '/:lookup/:content_type/', to: 'content#content_type', :as => "content_type", via: :get
    match '/:lookup/:content_type/gallery/:gallery_image', to: 'listings#gallery_image', :as => "gallery_image", via: :get

    match '/:lookup/reviews/all', to: 'reviews#index', via: :get
    match '/:lookup/shares/share', to: 'shares#show', :as => 'share', via: :get


    # resources :galleries, only: %i[index show] do
    #   resources :gallery_images, only: %i[show]
    # end
  end

  scope constraints: PlatformConstraint.new do
    get :authenticate_facebook_page, to: 'authentications#facebook_page'

    get 'stripe/connect/authorize', :to => 'businesses/accounts/stripe_authorizations#update'
    delete 'stripe/connect/deauthorize', :to => 'businesses/accounts/stripe_authorizations#destroy'

    devise_for :users, controllers: {
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      unlocks: 'users/unlocks',
    }

    devise_scope :user do
      authenticated :user do
        root to: 'businesses#index', as: :authenticated_root
      end
      unauthenticated :user do
        root to: 'users/sessions#new'
      end
      patch '/users/confirmation' => 'users/confirmations#update'
    end

    namespace :connect do
      get :locable, to: 'session_redirects#locable'
      get :receive_locable, to: 'session_creates#locable'
    end

    namespace :super do
      resources :communities
      resources :to_do_lists
      resources :event_feeds, except: [:show]
      resources :missions do
        get :custom, on: :collection
      end
      resources :guided_post_prompts do
        # get :custom, on: :collection
      end
      resources :billing_dashboard, only: [:none] do
        collection do

        end
      end
      resources :users, only: [:none] do
        collection do
          get :all_users
          get :super_admins
        end
      end
      resources :email_data, only: [:index] do
        collection do
          get :overview
        end
      end
      resources :business_data, only: [:index, :edit, :update] do
        member do
          get :merge_with
          get :select_merge_fields
          put :merge_now
          # put :update_community
        end
      end

      resources :subscription_plans
      resources :affiliates, only: [:index]
      resources :to_dos, only: :index
      resources :to_do_notification_settings, only: %i[index create]
      resources :subscriptions_data, only: [:none] do
        collection do
          get :subscription_stats
          get :subscriptions
          get :inactive_subscriptions
          get :all_subscriptions
          get :past_dues
        end
      end
    end

    resources :sns, only: [:none] do
      collection do
        post :bounce_data
        post :report_data
      end
    end

    namespace :widgets do
      get '/review_widgets/:uuid', to: 'review_widgets#index'
      get '/directory_widgets/:uuid', to: 'directory_widgets#index'
      get '/directory_widgets/:uuid/:business_id', to: 'directory_widgets#show', as: :directory_widget
      get '/content_feed_widgets/:uuid', to: 'content_feed_widgets#index'
      get '/content_feed_widgets/:uuid/:content_id', to: 'content_feed_widgets#show'
      get '/calendar_widgets/:uuid', to: 'calendar_widgets#index'
      get '/calendar_widgets/:uuid/:content_id', to: 'calendar_widgets#show'
      get '/contact_form_widgets/:uuid', to: 'contact_form_widgets#index'
      post '/contact_form_widgets/:uuid', to: 'contact_form_widgets#submit', as: :contact_form_submit
      get '/mercantile_embeds/:uuid', to: 'mercantile_embeds#index'
    end

    namespace :onboard do
      resources :users, only: %i[new create]
      resources :businesses, only: %i[create edit update], format: :json
      get '/businesses/:id/details', to: 'business_details#edit', as: :business_details
      patch '/businesses/:id/details', to: 'business_details#update', as: :business_details_update
      namespace :website do
        resources :businesses, only: %i[new create edit update destroy] do
          post :import_cce, on: :collection
          post :import_facebook, on: :collection
          resource :location, only: %i[edit update]
          resource :lines, only: %i[edit update]
          resource :delivery, only: %i[edit update]
          resource :customers, only: %i[edit update]
          resource :values, only: %i[edit update]
          resource :website, only: %i[edit update]
          resource :theme, only: %i[edit update]
        end
      end
    end

    resources :businesses, only: %i[index] do
      scope module: :businesses do
        resource :dashboard, path: '', only: %i[show]
        resource :dashboard_tour_viewed, only: %i[create]
        # resources :account_modules do
        #   get 'remote_create', :on => :collection
        # end

          resources :subscriptions, except: [:index] do
            resources :affiliate_payments, only: %i[show edit update] do
              get 'unpaid_affiliate_commissions', :on => :collection
              post 'mark_as_paid', :on => :collection
            end
            resources :affiliate_sales, only: %i[show index delete] do
              collection do
                get 'referred_businesses'
                get 'commissions'
              end
            end
            resources :subscription_payments, only: %i[show]
            collection do
              get :dashboard, :thanks, :plans, :canceled, :return_to_impact, :initial_plan_setup
              match 'billing' => "subscriptions#billing", via: [ :get, :post ]
              match 'setup_billing' => 'subscriptions#initial_billing_setup', via: [ :get, :post ]
              #^setup_billing is the initial billing page a user would encounter when they sign-up;
              #afterwards, subscriptions#billing is used. #enter_billing_information is sleeker
              #than #billing and presents a better image to first-time customers.
              match 'plan' => "subscriptions#plan", via: [ :get, :post ]
              get 'billing_history'
              get 'subscription_dashboard'
            end
          end

        namespace :events do
          root to: 'feeds#show'
        end

        namespace :content do
          root to: 'feeds#show'
          get '/new', to: 'roots#show'
          get '/activate', to: 'base#index'
          resource :images_upload, only: %i[new create]
          resource :feed, only: %i[show]
          resources :before_afters, only: %i[new create edit update destroy] do
            resources :shares, only: %i[new create]
            get :sharing_insights
          end
          resources :event_definitions, only: %i[new create edit update destroy], path: 'events' do
            resources :shares, only: %i[new create]
            get :sharing_insights
            get :clone, on: :member
          end
          resources :event_feeds, except: [:index] do
            post :reprocess, on: :member
            resources :imported_event_definitions, except: [:show, :index, :new, :create]
          end
          resource :event_import_notifications, only: %i[edit update]

app/controllers/businesses/accounts/facebooks_controller.rb
class Businesses::Accounts::FacebooksController < Businesses::BaseController
  before_action only: %i[edit update] do
    if @business.facebook_id? && @business.facebook_token?
      oauth = Koala::Facebook::OAuth.try(:new, Rails.application.secrets.facebook_app_id, Rails.application.secrets.facebook_app_secret, nil)

      begin
        graph = Koala::Facebook::API.try(:new, @business.facebook_token)
        @linked_facebook_page = graph.try(:get_object, @business.facebook_id).try(:with_indifferent_access)
      rescue
        # handle users that have logged out/changed pw
        graph = Koala::Facebook::API.try(:new, oauth.get_app_access_token)
        @linked_facebook_page = graph.try(:get_object, @business.facebook_id).try(:with_indifferent_access)
      end
    end
  end

  def edit
    if @business.facebook_id? && @business.facebook_token? && @linked_facebook_page && !@linked_facebook_page.nil?
      @linked_facebook_page
      redirect_to business_accounts_root_path(@business)
    else
      @linked_facebook_page = nil
    end
  end

  def update
    if @linked_facebook_page
      update_resource @business, facebook_automation_params, location: [:edit, @business, :accounts_facebook] do |success|
        if success
          if @business.automated_export_facebook_reviews == '1'
            FacebookReviewsExportJob.perform_later(@business)
          end
        end
      end
    else
      begin
        @business.facebook_id = facebook_id
        callback_url = url_for([:authenticate_facebook_page, business_id: @business.id, facebook_id: @business.facebook_id])
        oauth = Koala::Facebook::OAuth.new(Rails.application.secrets.facebook_app_id, Rails.application.secrets.facebook_app_secret, callback_url)
        redirect_to oauth.url_for_oauth_code(permissions: 'manage_pages publish_pages')
      rescue
        flash.now.alert = t('.alert')
        render :edit
      end
    end
  end

  def destroy
    @business = Business.find(params[:business_id])
    @business.update_columns(facebook_id: nil, facebook_token: nil)
    @business.automated_export_facebook_reviews = '0'
    respond_to do |format|
      format.js { redirect_to edit_business_accounts_facebook_path(@business), status: 303}
      format.json
    end
  end
  private

  def facebook_automation_params
    params.require(:business).permit(
      :automated_export_facebook_reviews,
    )
  end

  def facebook_id
    path = URI.parse(params[:business].try(:[], :facebook_id)).path rescue ''
    path.sub(/\A\//, '').split('/').first
  end
end

app/controllers/businesses/accounts/locables_controller.rb
class Businesses::Accounts::LocablesController < Businesses::BaseController
  before_action only: %i[edit update] do
    if @business.cce_id?
      @locable_business = LocableBusiness.find_by_id(@business.cce_id)
    end

    unless @locable_business
      @locable_user = LocableUser.find_by_email(current_user.email)
      if @locable_user
        @locable_businesses = @locable_user.businesses.to_a + @locable_user.managed_businesses.to_a
        @locable_sites = LocableSite.order(name: :asc).to_a
      end
    end
  end

  def update
    if @locable_business
      update_resource @business, locable_params, location: [:edit, @business, :accounts_locable] do |success|
        if success
          if @business.automated_export_locable_events == '1'
            LocableEventsExportJob.perform_later(@business)
          end
          if @business.automated_export_locable_reviews == '1'
            LocableReviewsExportJob.perform_later(@business)
          end
          if @business.automated_import_locable_reviews == '1'
            LocableReviewsImportJob.perform_later(@business)
          end
        end
      end
    else
      if params[:locable_id].present?
        locable_business = @locable_businesses.find { |record| record.id.to_s == params[:locable_id] }
        if locable_business && locable_business.link(@business, current_user, @locable_user)
          redirect_to [:edit, @business, :accounts_locable], notice: 'Your Locable account was successfully linked.'
        else
          redirect_to [:edit, @business, :accounts_locable], alert: 'There was a problem linking your Locable account.'
        end
      elsif params[:add_to_locable].present?
        locable_site = @locable_sites.find { |record| record.id.to_s == params[:site_id] }
        if locable_site
          locable_business = LocableBusiness.new
          if locable_business.create(@business, current_user, @locable_user, locable_site)
            redirect_to [:edit, @business, :accounts_locable], notice: 'Your Locable account was successfully created.'
          else
            redirect_to [:edit, @business, :accounts_locable], alert: 'There was a problem creating your Locable business.'
          end
        else
          redirect_to [:edit, @business, :accounts_locable], alert: 'Please provide a valid Locable site.'
        end
      else
        locable_slug = params[:locable_url].to_s.split('/').last
        locable_business = LocableBusiness.find_by_slug(locable_slug)
        if locable_slug.present? && locable_business
          if locable_business.claimed?
            if current_user.super_user? || locable_business.users.include?(@locable_user) || @locable_user.businesses.include?(current_user)
              if locable_business.link(@business, current_user, @locable_user)
                redirect_to [:edit, @business, :accounts_locable], notice: 'Your Locable account was successfully linked.'
              else
                redirect_to [:edit, @business, :accounts_locable], alert: 'There was a problem linking your Locable listing.'
              end
            else
              redirect_to [:edit, @business, :accounts_locable], alert: 'It looks like that listing has already been claimed.'
            end
          else
            if locable_business.claim(@business, current_user, @locable_user)
              redirect_to [:edit, @business, :accounts_locable], notice: 'Your Locable account was successfully claimed.'
            else
              redirect_to [:edit, @business, :accounts_locable], alert: 'There was a problem claiming your Locable listing.'
            end
          end
        else
          redirect_to [:edit, @business, :accounts_locable], alert: 'We could not find that business.'
        end
      end
    end
  end

  def destroy
    locable_business = LocableBusiness.find(@business.cce_id)
    if locable_business.unlink(@business)
      respond_to do |format|
        format.js { 
            redirect_to business_accounts_root_path(@business), status: 303
          }
        format.json { locable_business.unlink(@business) }
      end
    else
      redirect_to [:edit, @business, :accounts_locable], alert: 'There was a problem unlinking your Locable account.', status: 303
    end
  end

  private

  def locable_params
    params.require(:business).permit(
      :automated_export_locable_events,
      :automated_export_locable_reviews,
      :automated_import_locable_events,
      :automated_import_locable_reviews,
    )
  end
end

app/controllers/businesses/accounts/roots_controller.rb
class Businesses::Accounts::RootsController < Businesses::BaseController

	def show
	  @business = Business.find(params[:business_id])
	  @linked_facebook_page =  @business.facebook_id? && @business.facebook_token?
	  @locable_business =  @business.cce_id?
	end
end

app/controllers/businesses/alliances_controller.rb
class Businesses::AlliancesController < Businesses::BaseController
end

app/views/businesses/subscriptions/cancel.html.erb
<h1><%= @page_title = 'Cancel Account' %></h1>

<p>You are about to cancel your account.  This will <strong>permanently delete all your data</strong>.  Once you do this, you will no longer have access to your data, so be sure this is really what you want to do. </p>

<h2>Wait!  Before you go...</h2>
<p>
  Instead of canceling your account, perhaps you'd like to just switch your plan.  <a href="/account/plan">Change your subscription level now</a>.
</p>

<%= form_tag :action => 'cancel' do %>
  <fieldset>
    <legend>Cancel Confirmation</legend>

    <input type="checkbox" name="confirm" class="checkbox" value="1" />
    I really do want to cancel my account and delete all my data.
  </fieldset>

  <%= submit_or_cancel '/account', 'Delete my Account' %>
<% end %>

app/views/businesses/subscriptions/edit.html.erb
<h1>Change account settings</h1>

<%= simple_form_for @account, :url => { :action => 'update' }, :html => { :method => :put } do |f| %>
  <%= f.input :name %>
  <%= submit_or_cancel :action => 'show' %>
<% end %>

app/views/businesses/subscriptions/initial_billing_setup.html.erb
<% content_for :title do %>
  Enter Billing Information
<% end %>


<div class="col-lg-12">
  <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissable" role="alert">
          <%= flash[:notice] %>
      </div>
  <% end %>
  <% if params[:missing_billing] == "true" %>
      <div class="alert alert-success alert-dismissable" role="alert">
        Oops! We're missing billing information for the 
        <%=@business.subscription.subscription_plan.name%> Plan. If you chose
        this plan in error, click
        <%= link_to plan_business_subscriptions_path do %>
          here
        <% end %>
        to get back on the free "Engage" Plan. Otherwise, please enter and submit your
        billing information below.
      </div>
  <% end %>
  <div class="ibox">
    <div class="ibox-title">
      <h2> Kindly Submit Your Payment Information to Activate Your Subscription.
        </br> 
<!--         If You Selected the Wrong Plan and Need to Go Back,
        <#%= link_to initial_plan_setup_business_subscriptions_path(@business, :back => "true") do %>
            Click Here.
        <%# end %> -->
    </div>
    <div class="ibox-content">
      <div class="panel-group payments-method" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            Enter Your Credit Card Information Below
          </div>
          <div id="collapseTwo" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-4">
                  <h2>Summary</h2>
                  <strong>
                    Plan: 
                  </strong>
                  <p>
                    <%= @subscription_plan.name %>
                  </p>
                  <strong>
                    Today's Charges: 
                  </strong>
                  <p>
                    Subscription fee:
                    <%= number_to_currency @amount %>
                    </br>
                    One-time setup fee:
                    <%= number_to_currency @subscription_plan.setup_amount %>
                    </br>
                    <b><ul>Total:
                    <%= number_to_currency (@amount + @subscription_plan.setup_amount) %></ul></b>
                  </p>

                  <strong>Next charge date:</strong>
                  <p>
                    <% if @subscription.annual == true && @subscription.flagged_for_annual == true || @subscription.flagged_for_annual == true %>
                      <%= (Time.now + 1.years).to_date.to_formatted_s(:long_ordinal)%>
                    <% else %>
                      <%= (Time.now + 1.months).to_date.to_formatted_s(:long_ordinal)%>
                    <% end %>
                  </p>
                  <strong>Next charge amount:</strong>
                  <p>
                    Subscription:
                    <%= number_to_currency @amount %>
                  </p>
                  <strong>Current payment method:</strong>
                  <p>
                    <% if @subscription.card_number && @subscription.card_expiration %>
                      <%= "#{@subscription.card_number} / #{@subscription.card_expiration}" %>
                    <% else %>
                      No credit card information is on file. Please use the form on this page to submit this information.
                    <% end %>
                  </p>

                </div>
                <div class="col-md-8">
                  <% if @subscription.state == 'trial' %>
                    <% if @subscription.next_renewal_at > Time.now %>
                      <p>
                        Thank you for trying <%= Saas::Config.app_name %>!  Your trial account will expire in <%= pluralize(@subscription.trial_days, 'day', 'days') %>, at which time you will no longer have access to your account.  To maintain access to your account, enter your credit card information below.  Your first charge will happen on <%= @subscription.next_renewal_at.to_date.to_formatted_s(:long_ordinal)%>.
                      </p>
                    <% else %>
                      To upgrade your account to your plan, enter your credit card information below.  Your first charge will happen immediately, and you will be billed monthly thereafter.
                    <% end %>
                  <% end %>

                  <%= render 'initial_billing_setup_credit_card_form'  %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <%= javascript_include_tag 'stripe_form' %>
  <script type="text/javascript">
    // this identifies your website in the createToken call in stripe_form.js
    Stripe.setPublishableKey('<%= Saas::Config.credentials['stripe_publishable_key'] %>');
  </script>
<% end if Saas::Config.gateway == 'stripe' and Saas::Config.credentials['stripe_publishable_key'] %>

app/views/businesses/subscriptions/subscription_dashboard.html.erb
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h1><%= @page_title = 'Manage Subscription and Billing' %></h1>
  </div>
  <div class="ibox-content">
    <% if @subscription.nil? %>
      <p>
        Our records show you don't have a subscription on file. Click below to get started.
        <p>
          <%= link_to 'Set Up My Subscription', plan_business_subscriptions_path(@business), class: "btn btn-primary" %>
        </p>
      </p>
    <% else %>

      <p>
        You can change your plan level at any time.  If you are moving up from a free to a paid subscription, features of the new plan that you select will be effective once you've submitted your billing information. Don't worry, we'll prompt you for it once you've upgraded! If your billing information is already in our systems, your new plan will take place immediately. Your bill amount will not change until your next bill date.
      </p>
      <p>
        <b>
          <% if @subscription.amount > 0 && @subscription.downgrade_to.nil? %>
            Your next bill date is <%= @subscription.next_renewal_at.to_date.to_formatted_s(:long_ordinal)%>.
          <% else %>
            You currently have no monthly or annual charges.
          <% end %>
        </b>
      </p>

      <% if @subscription.needs_payment_info? %>
        <p><b>
          We have no payment information from you on file. Please make sure you <%= link_to('enter your billing information', billing_business_subscriptions_url(@business)) %> before your bill date to prevent an interruption in service.
        </b></p>
      <% end %>

    <% end %>
  </div>
</div>

<% if !@subscription.nil? %>
  <% if @subscription && @subscription.errors.any? %>
    <div class="errorExplanation">
      <h2>Errors encountered with your change:</h2>
      <ul>
        <%= raw(@subscription.errors.full_messages.map {|m| content_tag('li', m)}) %>
      </ul>
    </div>
  <% end %>


  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h2>Manage Your Plan</h2>
    </div>

    <div class="ibox-content">

      <h3>
        You are subscribed to the 
        <% if @subscription.annual? %>
          <strong><%= @subscription.subscription_plan.name %> Plan ( <%= number_to_currency(@subscription.amount)%> / year ). </strong>
        <% elsif !@subscription.annual? && @subscription.amount > 0 %>
          <strong><%= @subscription.subscription_plan.name %> Plan ( <%= number_to_currency(@subscription.amount)%> / month ). </strong>
        <% else %>
          <strong> <%= @subscription.subscription_plan.name %> Plan (free). </strong>
        <% end %>
        <% if !@subscription.downgrade_to.nil? %>
          </br>
          <strong>However, you are scheduled to switch over to the <%=@new_subscription %> Plan on <%= @subscription.next_renewal_at.to_date.to_formatted_s(:long_ordinal)%>. 
          </br>
            If this was done in error, click 'Keep My Old Plan' below <u>before</u> <%= @subscription.next_renewal_at.to_date.to_formatted_s(:long_ordinal)%>.</strong>
          <p>
            <%= button_to 'Keep My Old Plan', {action: "plan", revert: "true"}, class: "btn btn-primary" %>
          </p>
        <% end %>
      </h3>

      <p>
        <% if @subscription.needs_payment_info? || @subscription.inactive? %>
          <strong> NOTICE: Your subscription is not active because you have not provided billing information. Please do so to prevent an interruption in service.</strong>
          </br>
        <% end %>
        If you want to change your plan, please click the "Change My Plan" button.
      </p>
      <p>
        <%= link_to 'Change My Plan', plan_business_subscriptions_path(@business), class: "btn btn-primary" %>
      </p>
    </div>
  </div>


  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h2>Manage Billing Information</h2>
    </div>

    <div class="ibox-content">

      <p style="padding-top:1em">
        <label>Current payment method:</label>
        <% if @subscription.card_number && @subscription.card_expiration %>
          <%= "#{@subscription.card_number} / #{@subscription.card_expiration}" %>
        <% elsif @subscription.needs_payment_info? && @subscription.amount > 0 %>
          </br>
          <b> There is no billing information in our systems. </b>
          Please click "Manage Billing" below to add your billing information before your bill date to prevent an interruption in service.
        <% else %>
          </br>
          <b> You are on a free plan and do not need to submit any billing information at this time. </b>
        <% end %>
      </p>
      <p>
        <%= link_to 'Manage Billing', billing_business_subscriptions_url(@business), class: "btn btn-primary" %>
      </p>
    </div>
  </div>

  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h2>Billing History</h2>
    </div>
    <div class="ibox-content">
      <p style="padding-top:1em">
        <% if @subscription.subscription_payments %>
          Click below to see your billing history.
        <% elsif @subscription.needs_payment_info? && @subscription.amount > 0 %>
          </br>
          <b> There is no billing history in our systems. </b>
          Please click "Manage Billing" above to add your billing information before your bill date to prevent an interruption in service.
        <% end %>
      </p>
      <p>
        <%= link_to 'Billing History', billing_history_business_subscriptions_path(@business), class: "btn btn-primary" %>
      </p>
    </div>
  </div>

  <% if @business.is_affiliate? %>
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h2>Affiliate Information & History</h2>
      </div>
      <div class="ibox-content">
        <% if !@business.affiliate_activated? %>
          <p style="padding-top:1em">
            Your affiliate program is currently disabled. Please contact
            support for further information.
          </p>        
        <% elsif @business.affiliate_activated? %>
          <span class="pull-right">
              <h3>Current Balance: <%=number_to_currency(@balance)%></h3>
          </span>
          <p style="padding-top:1em">
            <%= link_to 'Affiliate History', business_subscription_affiliate_sales_path(@business, @subscription), class: "btn btn-primary" %>
          </p>
          </br>
          <p>
            <b> Your unique URL: </b>
            </br>
            <b> <%= @business.unique_affiliate_url(root_url) %> </b>
            </br>
            Share this unique URL to earn benefits from bringing in new
            users. You will only earn benefits if users sign-up via
            your unique URL.
          </p>
        <% end %>
      </div>
    </div>
  <% end %>

<% end %>


<script type="text/javascript" charset="utf-8">
  function enableButton() {
    document.getElementById('commit').disabled = document.forms[0].elements['plan_id'].selectedIndex == 0
  }
  enableButton();
</script>

app/views/businesses/subscriptions/thanks.html.erb
<h1>Account created</h1>

<p>
  Thank you for creating an account!  You can now log in to your account at <a href="http://<%= flash[:domain] %>.<%= request.host_with_port %>/">http://<%= flash[:domain] %>.<%= request.host_with_port %>/</a>.
</p>